AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: nodejs20.x
    CodeUri: .
    Architectures:
      - x86_64

Resources:
  # lambda function
  TheconversationWebScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/theconversation/app.lambdaHandler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NewsTable
            Effect: Allow
            Action:
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
            PolicyName: NewsTableWritePolicy
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - api/theconversation/app.ts

  # dynamodb config
  NewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: NewsTable
