AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  # lambda function
  TheconversationWebScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: api/theconversation/app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 15
      Architectures:
        - x86_64
      Policies:
        - PolicyName: NewsTableWritePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                Resource: NewsTable

  # dynamodb config
  NewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: newsId
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: NewsTable
