version: "3.8"
services:
  rssfeed-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rssfeed-web
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .next:/app/.next
    networks:
      - rssfeed-net

volumes:
  node_modules:
  .next:

networks:
  rssfeed-net:
    driver: bridge
